# Generated by Django 2.1 on 2020-05-19 05:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'environments',
            },
        ),
        migrations.CreateModel(
            name='ImpactDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'impact_details',
            },
        ),
        migrations.CreateModel(
            name='ModuleDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'module_details',
            },
        ),
        migrations.CreateModel(
            name='OsAndDeviceDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=125)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'os_and_device_details',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=50)),
                ('updated_by', models.CharField(default='system', max_length=50)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'test_cases',
            },
        ),
        migrations.CreateModel(
            name='TestCaseDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impact_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.ImpactDetail')),
                ('module_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.ModuleDetail')),
                ('os_and_device_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.OsAndDeviceDetail')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.TestCase')),
            ],
            options={
                'db_table': 'test_case_details',
            },
        ),
        migrations.CreateModel(
            name='TestCaseOutput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expect_output', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'test_case_outputs',
            },
        ),
        migrations.CreateModel(
            name='TestCaseRemarkDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'test_case_remark_detail',
            },
        ),
        migrations.CreateModel(
            name='TestCaseStepDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_step', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'test_case_step_details',
            },
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'testers',
            },
        ),
        migrations.CreateModel(
            name='TestScript',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=50)),
                ('updated_by', models.CharField(default='system', max_length=50)),
            ],
            options={
                'db_table': 'test_scripts',
            },
        ),
        migrations.CreateModel(
            name='TestScriptDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.Environment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.Project')),
                ('test_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.TestScript')),
            ],
            options={
                'db_table': 'test_script_details',
            },
        ),
        migrations.AlterIndexTogether(
            name='testscript',
            index_together={('title', 'created_at', 'created_by'), ('title', 'created_at', 'updated_by'), ('title', 'updated_at', 'created_by'), ('title', 'updated_at', 'updated_by')},
        ),
        migrations.AddField(
            model_name='testcasedetail',
            name='test_case_output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.TestCaseOutput'),
        ),
        migrations.AddField(
            model_name='testcasedetail',
            name='test_case_remark_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapps.TestCaseRemarkDetail'),
        ),
        migrations.AddField(
            model_name='testcasedetail',
            name='test_case_step_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapps.TestCaseStepDetail'),
        ),
        migrations.AddField(
            model_name='testcasedetail',
            name='test_script_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.TestScriptDetail'),
        ),
        migrations.AddField(
            model_name='testcasedetail',
            name='tester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapps.Tester'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_scripts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.TestScript'),
        ),
        migrations.AlterIndexTogether(
            name='project',
            index_together={('title', 'created_at', 'created_by'), ('title', 'created_at', 'updated_by'), ('title', 'updated_at', 'created_by'), ('title', 'updated_at', 'updated_by')},
        ),
    ]
