# Generated by Django 2.1 on 2020-05-19 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'test_case_descriptions',
            },
        ),
        migrations.AddField(
            model_name='testcasedetail',
            name='test_case_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapps.TestCaseDescription'),
        ),
    ]
