# Generated by Django 2.1 on 2020-05-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapps', '0002_auto_20200520_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='test_scripts',
            new_name='test_script',
        ),
    ]
