# Generated by Django 2.1 on 2020-05-20 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapps', '0003_auto_20200520_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_script_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.TestScriptDetail')),
            ],
            options={
                'db_table': 'test_case_card',
            },
        ),
        migrations.CreateModel(
            name='TestCaseCardDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('impact_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.ImpactDetail')),
                ('module_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.ModuleDetail')),
                ('os_and_device_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.OsAndDeviceDetail')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.TestCase')),
                ('test_case_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.TestCaseCard')),
                ('test_case_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapps.TestCaseDescription')),
                ('test_case_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.TestCaseOutput')),
                ('test_case_remark_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapps.TestCaseRemarkDetail')),
                ('test_case_step_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapps.TestCaseStepDetail')),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapps.Tester')),
            ],
            options={
                'db_table': 'test_case_card_detail',
            },
        ),
        migrations.RemoveField(
            model_name='testcasedetail',
            name='impact_detail',
        ),
        migrations.RemoveField(
            model_name='testcasedetail',
            name='module_detail',
        ),
        migrations.RemoveField(
            model_name='testcasedetail',
            name='os_and_device_detail',
        ),
        migrations.RemoveField(
            model_name='testcasedetail',
            name='test_case',
        ),
        migrations.RemoveField(
            model_name='testcasedetail',
            name='test_case_description',
        ),
        migrations.RemoveField(
            model_name='testcasedetail',
            name='test_case_output',
        ),
        migrations.RemoveField(
            model_name='testcasedetail',
            name='test_case_remark_detail',
        ),
        migrations.RemoveField(
            model_name='testcasedetail',
            name='test_case_step_detail',
        ),
        migrations.RemoveField(
            model_name='testcasedetail',
            name='test_script_detail',
        ),
        migrations.RemoveField(
            model_name='testcasedetail',
            name='tester',
        ),
        migrations.DeleteModel(
            name='TestCaseDetail',
        ),
    ]
