# Generated by Django 2.1 on 2020-05-21 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapps', '0004_auto_20200520_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='test_script',
        ),
        migrations.RemoveField(
            model_name='testcasecarddetail',
            name='test_case',
        ),
        migrations.RemoveField(
            model_name='testcaseoutput',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testcaseoutput',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='testcasecard',
            name='test_case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapps.TestCase'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='project',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='testscript',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='testscript',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testscript',
            name='updated_by',
        ),
    ]
