# Generated by Django 2.1 on 2020-05-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapps', '0006_auto_20200522_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasecarddetail',
            name='impact_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapps.ImpactDetail'),
        ),
        migrations.AlterField(
            model_name='testcasecarddetail',
            name='module_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapps.ModuleDetail'),
        ),
        migrations.AlterField(
            model_name='testcasecarddetail',
            name='os_and_device_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapps.OsAndDeviceDetail'),
        ),
        migrations.AlterField(
            model_name='testcasecarddetail',
            name='test_case_output',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapps.TestCaseOutput'),
        ),
    ]
