# Generated by Django 2.1 on 2020-05-22 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapps', '0007_auto_20200522_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImpactDetail',
            new_name='StatusDetail',
        ),
        migrations.RenameField(
            model_name='testcasecarddetail',
            old_name='impact_detail',
            new_name='status_detail',
        ),
        migrations.RemoveField(
            model_name='testcasecard',
            name='test_case',
        ),
        migrations.RemoveField(
            model_name='testcasecarddetail',
            name='test_case_description',
        ),
        migrations.RemoveField(
            model_name='testcasecarddetail',
            name='test_case_output',
        ),
        migrations.RemoveField(
            model_name='testcasecarddetail',
            name='test_case_remark_detail',
        ),
        migrations.RemoveField(
            model_name='testcasecarddetail',
            name='test_case_step_detail',
        ),
        migrations.AddField(
            model_name='testcasecard',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcasecarddetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcasecarddetail',
            name='expect_output',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testcasecarddetail',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testcasecarddetail',
            name='test_step',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='statusdetail',
            table='status_details',
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
        migrations.DeleteModel(
            name='TestCaseDescription',
        ),
        migrations.DeleteModel(
            name='TestCaseOutput',
        ),
        migrations.DeleteModel(
            name='TestCaseRemarkDetail',
        ),
        migrations.DeleteModel(
            name='TestCaseStepDetail',
        ),
    ]
