# Generated by Django 2.1 on 2020-05-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapps', '0008_auto_20200522_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusdetail',
            name='is_active',
        ),
    ]
