# Generated by Django 2.1 on 2020-05-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapps', '0010_remove_osanddevicedetail_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasecarddetail',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testcasecarddetail',
            name='expect_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcasecarddetail',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
