# Generated by Django 2.1 on 2020-06-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapps', '0011_auto_20200526_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseCardDetailImg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='attachments/%Y/%m/%d/')),
                ('test_case_card_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapps.TestCaseCardDetail')),
            ],
        ),
    ]
