# Generated by Django 2.1 on 2020-06-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapps', '0012_testcasecarddetailimg'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testcasecarddetailimg',
            table='test_case_card_detail_img',
        ),
    ]
